### ISSUE TITLE
Question: Multiple configmap?

### ISSUE THREAD

**Issue by saikatharryc** [jakubkulhan/ingress-merge#10]
I have multiple charts, and they have their own configmaps , and resources defined inside the templates of each helm chart.
just wanted to know, wherever we define, ingress.yaml in that adding the same configmap.yaml will be supported or how you suggest using?
let me know in case not able to demonstrate my query.

**Comment by jakubkulhan** [comment]
Hi, configmap specifies settings for single merged ingress. If you want multiple ingresses from Helm chart releases to be merged into one, you should create configmap outside the chart and the chart's ingress should only have annotation specifying configmap name.

**Comment by saikatharryc** [comment]
got it! thanks!
