### ISSUE TITLE
doesn't owner health-check endpoint

### ISSUE THREAD

**Issue by rverma-nikiai** [jakubkulhan/ingress-merge#3]
If we annotate a particular ingress with custom health check endpoint using 
alb.ingress.kubernetes.io/healthcheck-path: /cust

The same is not automatically reflected in the required target group. Also, it would be great if the target group name can have the actual ingress name rather than ingress-merge.

**Comment by rverma-nikiai** [comment]
for reference of others, we need to apply health-check annotation on svc to override the default.

**Comment by jakubkulhan** [comment]
Hello @rverma-nikiai. If you need the resulting ingress to have annotations, you may in a `ConfigMap` referenced from partial ingress resources. See https://github.com/jakubkulhan/ingress-merge#configuration-keys
